# all files with final keywords
keywords_cancel_culture_path: 'data/keywords/cancel_culture_keywords.txt'
keywords_feminism_path: 'data/keywords/feminism_keywords.txt'
keywords_lgbtq_plus_path: 'data/keywords/lgbtq_plus_keywords.txt'
keywords_ageism_path: 'data/keywords/ageism_keywords.txt'
keywords_lookism_path: 'data/keywords/lookism_keywords.txt'

# all files with raw data
raw_data_cancel_culture_path: 'data/raw_data/cancel_culture_all_data.csv'
raw_data_feminism_path: 'data/raw_data/feminism_all_data.csv'
raw_data_lgbtq_plus_path: 'data/raw_data/lgbtq_plus_all_data.csv'
raw_data_ageism_path: 'data/raw_data/ageism_all_data.csv'
raw_data_lookism_path: 'data/raw_data/lookism_all_data.csv'

# all files with cleaned data
clean_data_cancel_culture_path: 'data/cleaned_data/cancel_culture_clean.csv'
clean_data_feminism_path: 'data/cleaned_data/feminism_clean.csv'
clean_data_lgbtq_plus_path: 'data/cleaned_data/lgbtq_plus_clean.csv'
clean_data_ageism_path: 'data/cleaned_data/ageism_clean.csv'
clean_data_lookism_path: 'data/cleaned_data/lookism_clean.csv'

# total cleaned dataset
unlabeled_all_data_path: 'data/cleaned_data/data_for_labeling.csv'

# all files with labeled data (after toloka)
labeled_all_data_path: 'data/labeled_data/all_data_labeled.csv'
labeled_data_cancel_culture_path: 'data/labeled_data/cancel_culture_labeled.csv'
labeled_data_feminism_path: 'data/labeled_data/feminism_labeled.csv'
labeled_data_lgbtq_plus_path: 'data/labeled_data/lgbtq_plus_labeled.csv'
labeled_data_ageism_path: 'data/labeled_data/ageism_labeled.csv'
labeled_data_lookism_path: 'data/labeled_data/lookism_labeled.csv'

# all files with preprocessed labeled data
preprocessed_all_data_path: '/data/preprocessed_data/all_data_preprocessed.csv'
preprocessed_data_cancel_culture_path: '/data/preprocessed_data/cancel_culture_preprocessed.csv'
preprocessed_data_feminism_path: '/data/preprocessed_data/feminism_preprocessed.csv'
preprocessed_data_lgbtq_plus_path: '/data/preprocessed_data/lgbtq_plus_preprocessed.csv'
preprocessed_data_ageism_path: '/data/preprocessed_data/ageism_preprocessed.csv'
preprocessed_data_lookism_path: '/data/preprocessed_data/lookism_preprocessed.csv'